# This workflow runs on every push to main. It does the following:
#   1. Checks if black formatting is followed.
#   2. Runs all tests.

name: lint
on:
  pull_request:
  push:
    branches:
      - 'main*'

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.0